openapi: 3.0.0
info:
  title: xmlStarlet API Server
  version: "1.2.0"
  description: >
    API for XML processing using xmlStarlet.
    This API provides endpoints to extract data, validate, transform, and format XML files.
servers:
  - url: /api
paths:
  /extract:
    post:
      summary: Extract values from an XML file
      description: >
        Executes an XPath expression against a provided XML file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: >
                    The path to the XML file. Must match the pattern: `/app/xmlfiles/{filename}.xml`
                xpath:
                  type: string
                  description: The XPath expression to evaluate.
              required:
                - filePath
                - xpath
      responses:
        '200':
          description: Extraction successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: The extracted value.
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /validate:
    post:
      summary: Validate an XML file
      description: >
        Validates that an XML file is well-formed (and optionally against a schema).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: >
                    The path to the XML file to validate. Must match the pattern: `/app/xmlfiles/{filename}.xml`
              required:
                - filePath
      responses:
        '200':
          description: XML is valid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
  /transform:
    post:
      summary: Transform an XML file using an XSLT stylesheet
      description: >
        Applies an XSLT transformation to an XML file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                xmlFilePath:
                  type: string
                  description: >
                    The path to the source XML file. Must match the pattern: `/app/xmlfiles/{filename}.xml`
                xsltFilePath:
                  type: string
                  description: >
                    The path to the XSLT file. Must match the pattern: `/app/xmlfiles/{filename}.xslt`
              required:
                - xmlFilePath
                - xsltFilePath
      responses:
        '200':
          description: Transformation successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: The transformed XML output.
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Transformation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
  /format:
    post:
      summary: Format (pretty-print) an XML file
      description: >
        Formats the XML file for improved readability.
        If an optional `saveTo` parameter is provided (and is not empty), the formatted XML is saved to that file path.
        Otherwise, the formatted XML is returned in the API response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: >
                    The path to the XML file to format. Must match the pattern: `/app/xmlfiles/{filename}.xml`
                saveTo:
                  type: string
                  description: >
                    (Optional) The destination path to save the formatted XML.
                    Must match the pattern: `/app/xmlfiles/{filename}.xml`
              required:
                - filePath
      responses:
        '200':
          description: Formatting successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: >
                      The formatted XML if no destination path is provided.
                  message:
                    type: string
                    description: >
                      A confirmation message when the formatted XML is saved.
        '400':
          description: Invalid request parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Formatting error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string